## Inspiration from https://github.com/sdsawtelle/markdown-resume

name: Create Resume
on: [push]
jobs:
  build_resume_html:
    runs-on: ubuntu-latest
    container: 
      image: pandoc/core:latest
      volumes:
        - ${{ github.workspace }}:/build:rw
    steps:
      - uses: actions/checkout@v2
      - run: pandoc --help
      - run: pandoc --standalone --metadata pagetitle="RESUME" -c stylesheet.css README.md -o resume.html
      - name: Upload Resume artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resume_html
          path: |
            stylesheet.css
            resume.html
            photo.jpg
  build_resume_pdf:
    needs: build_resume_html
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: resume_html
      - run: ls
      - run: docker run -v `pwd`:/build surnet/alpine-wkhtmltopdf:3.15.0-0.12.6-full --zoom 1.2 --enable-local-file-access /build/resume.html /build/resume.pdf 
      - name: Upload Resume artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resume_pdf
          path: |
            resume.pdf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: resume.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf
  deploy_to_pages:
    needs: build_resume_html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: resume_html
          path: build
      - run: mv build/resume.html build/index.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
