## Inspiration from https://github.com/sdsawtelle/markdown-resume

name: Create Resume
on: [push]
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: |
          export TAG=${GITHUB_SHA:0:8}
          echo "$DOCKER_PASSWORD" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin
          docker build -t ghcr.io/chaintng/pandoc-wkhtml:latest .
          docker push ghcr.io/chaintng/pandoc-wkhtml:latest
        env:
          DOCKER_USERNAME: ${{ github.repository }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  build_resume:
    needs: build_image
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/chaintng/pandoc-wkhtml
      volumes:
        - ${{ github.workspace }}:/build:rw
    steps:
      - uses: actions/checkout@v2
      - run: pandoc --help
      - run: pandoc --standalone --metadata pagetitle="RESUME" -c stylesheet.css README.md -o resume.html
      # - run: pandoc -f gfm -t html5 --metadata pagetitle="RESUME" -c stylesheet.css README.md -o resume.pdf
      ## TODO run on linux
      # - run: docker run 
      #     -v ${{ github.workspace }}:/build
      #     --entrypoint "sh -c"
      #     kannkyo/pandoc-wkhtmltopdf:latest 
      #     "pandoc -o resume.html -c resume-css-stylesheet.css README.md"
      ## TODO wkhtmltopdf doesn't work on 64bit
      # - run: wkhtmltopdf resume4.html resume.pdf 
      - name: Upload Resume artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: |
            stylesheet.css
            resume.html
            photo.jpg
      ## TODO Deploy in Pages
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: build # The folder the action should deploy.
  build_pdf:
    needs: build_resume
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: resume
      - run: ls
      - run: docker run -v ${pwd}:./ surnet/alpine-wkhtmltopdf:3.15.0-0.12.6-full resume.html resume.pdf 
      - name: Upload Resume artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resume_pdf
          path: |
            resume.pdf
