## Inspiration from https://github.com/sdsawtelle/markdown-resume

name: Create Resume
on: [push]
jobs:
  build_html_resume:
    runs-on: ubuntu-latest
    container: 
      image: pandoc/core:latest
      volumes:
        - ${{ github.workspace }}:/build:rw
    steps:
      - uses: actions/checkout@v2
      - run: pandoc --help
      - run: pandoc --standalone --metadata pagetitle="RESUME" -c stylesheet.css README.md -o resume.html
      - name: Upload Resume artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html_resume
          path: |
            stylesheet.css
            resume.html
            photo.jpg
  build_pdf_resume:
    needs: build_html_resume
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: html_resume
      - run: ls
      - run: docker run -v `pwd`:/build surnet/alpine-wkhtmltopdf:3.15.0-0.12.6-full --zoom 1.2 --enable-local-file-access /build/resume.html /build/resume.pdf 
      - name: Upload Resume artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resume_pdf
          path: |
            resume.pdf
  deploy_to_pages:
    needs: build_html_resume
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: html_resume
          path: /build
      ## TODO Deploy in Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: /build
